### ISSUE TITLE
run out of memory during  download

### ISSUE THREAD

**Issue by mandyozhao** [pivotal-cf-experimental/pivnet-resource#19]
we have a concourse worker running out of memory when it was trying to download a large file, error log attached, it seems like it was trying to read  the whole file at once when it calculates the md5

```
goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8200bee88 sp=0xc8200bee80
runtime.mallocgc(0xfffffe00, 0x6bfd60, 0xc800000001, 0x40000000)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc8200bef60 sp=0xc8200bee88
runtime.newarray(0x6bfd60, 0xfffffe00, 0xc8200bf000)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc8200befa0 sp=0xc8200bef60
runtime.makeslice(0x6b2a40, 0xfffffe00, 0xfffffe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc8200beff0 sp=0xc8200befa0
bytes.makeSlice(0xfffffe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:198 +0x64 fp=0xc8200bf040 sp=0xc8200beff0
bytes.(*Buffer).ReadFrom(0xc8200bf170, 0x7fdc51208298, 0xc820020030, 0x7ffffe00, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:170 +0xd3 fp=0xc8200bf0f0 sp=0xc8200bf040
io/ioutil.readAll(0x7fdc51208298, 0xc820020030, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x156 fp=0xc8200bf1e8 sp=0xc8200bf0f0
io/_ ioutil.ReadFile_(0xc82039c030, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:70 +0x19f fp=0xc8200bf2b0 sp=0xc8200bf1e8
github.com/pivotal-cf-experimental/pivnet-resource/md5.fileContentsSummer.Sum(0xc82039c030, 0x26, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf-experimental/pivnet-resource/md5/md5.go:26 +0x60 fp=0xc8200bf360 sp=0xc8200bf2b0
github.com/pivotal-cf-experimental/pivnet-resource/md5.(*fileContentsSummer).Sum(0xc8203cc040, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0xb0 fp=0xc8200bf398 sp=0xc8200bf360
github.com/pivotal-cf-experimental/pivnet-resource/in.(*InCommand).Run(0xc8200bfe98, 0xc8200ac740, 0x14, 0xc820010ff0, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf-experimental/pivnet-resource/in/in_command.go:157 +0x1e3c fp=0xc8200bfb20 sp=0xc8200bf398
main.main()
	/tmp/build/80754af9/gopath/src/github.com/pivotal-cf-experimental/pivnet-resource/cmd/in/main.go:52 +0xc2a fp=0xc8200bff40 sp=0xc8200bfb20
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8200bff90 sp=0xc8200bff40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200bff98 sp=0xc8200bff90
```

**Comment by robdimsdale** [comment]
@mandyozhao what version of the resource are you using? We fixed this (or something like it) in [v0.6.2](https://github.com/pivotal-cf-experimental/pivnet-resource/releases/tag/v0.6.2)

**Comment by zachgersh** [comment]
@mandyozhao shipped an RC to dockerhub.  Can you use the tag `v0.14.1-rc.3`

That now has the fix that @mmb added.

We can close this and ship an official patch release once confirmed!

**Comment by robdimsdale** [comment]
@mandyozhao @mmb based on the various PRs (#20,#21, and #22) I'm going to assume this works fine now, and I'll close this issue.

Thanks for bringing it to our attention and for submitting PRs to fix it!
